version: '3.8'

services:
  app:
    image: ghcr.io/juanfeliperestrepobuitrago/herzonteis/herzon_ecommerce:latest
    container_name: herzon_app
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/herzon_db
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: 123
    restart: always
    depends_on:
      - postgres
    networks:
      - app_network

  postgres:
    image: postgres:16
    container_name: herzon_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: herzon_db
      TZ: "America/Bogota"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: herzon_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@herzon.com
      PGADMIN_DEFAULT_PASSWORD: 123
    restart: always
    networks:
      - app_network

  # nginx:
  #   image: nginx:latest
  #   container_name: herzon_nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./certs:/etc/nginx/certs:ro
  #   restart: always
  #   depends_on:
  #     - app
  #     - pgadmin
  #   networks:
  #     - app_network

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - 80:80
      - 443:443
    restart: always
    environment:
      DOMAINS: "herzon.com -> http://prestashop:80"
      STAGE: 'staging' # Don't use production until staging works
      # FORCE_RENEW: 'true'
    networks:
      - frontend-network

networks:
  app_network:
    driver: overlay
    attachable: true

volumes:
  postgres_data: