services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: herzon_db
      TZ: "America/Bogota"
    ports:
      - "5432:5432"
    networks:
      - postgres_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@herzon.com
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - "8081:80"
    networks:
      - postgres_network

  app:
    image: ghcr.io/juanfeliperestrepobuitrago/herzonteis/herzon_ecommerce:latest
    restart: always
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/herzon_db
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: 123
    depends_on:
      - postgres
    ports:
      - "8082:8080"
    networks:
      - postgres_network

networks:
  postgres_network:
    driver: bridge
