version: '3.8'

services:
  app:
    image: ghcr.io/juanfeliperestrepobuitrago/herzonteis/herzon_ecommerce:latest
    deploy:
      mode: replicated
      replicas: 4
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/herzon_db
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: 123
    depends_on:
      - postgres
    networks:
      - app_network

  postgres:
    image: postgres:16
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: herzon_db
      TZ: "America/Bogota"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4:latest
    deploy:
      mode: replicated
      replicas: 1
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@herzon.com
      PGADMIN_DEFAULT_PASSWORD: 123
    networks:
      - app_network

  nginx:
    image: nginx:latest
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
      - pgadmin
    networks:
      - app_network

networks:
  app_network:
    driver: overlay
    attachable: true

volumes:
  postgres_data: