CREATE TABLE auctions (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    start_date TIMESTAMP NOT NULL,
    end_date TIMESTAMP NOT NULL,
    start_price DECIMAL(19,2) NOT NULL,
    current_price DECIMAL(19,2) NOT NULL
);

CREATE TABLE offers (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    offer_price DECIMAL(19,2) NOT NULL,
    state BOOLEAN NOT NULL DEFAULT TRUE,
    auction_id BIGINT NOT NULL,
    FOREIGN KEY (auction_id) REFERENCES auctions(id)
);