name: Checkstyle Validation

on: [push, pull_request]

jobs:
  checkstyle:
    name: 'Checkstyle Validation'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: oracle
      
      - name: Run Checkstyle
        run: ./mvnw clean checkstyle:check